### PR TITLE
Update scroll.js

### PR DESCRIPTION
**Pull request by Shirley89**
function 'onExpandScroll' and 'onShrinkScroll' throw an error, getState(element) return undefined, judge getState(element)

### CODE REVIEW

**Comment by wnr** [comment]
Hi, sorry for the late response. Could you provide some background regarding this issue? I'm a bit reluctant to add such fixes that only avoids throwing exceptions rather than fixing the real underlying issue. If the getState function returns null at this point, the whole system is in an undefined errornous state, and we need to ensure that does not happen rather than muting the exception. Can you reproduce this?

**Comment by xxx** [comment]
@wnr I'm not the creator of this issue, but my entire team is also seeing these warnings on certain page loads. This module is a dependency of [react-sizeme](https://github.com/ctrlplusb/react-sizeme), which is where our use comes from.

**Comment by wnr** [comment]
@xxx I understand. As I said, this PR will only mute the exceptions and not solve the real issue. Please open an issue at react-sizeme so that they can debug this issue. These symptoms are often caused due to invalid use of this library - that elements are being removed or having its children overwritten before calling `uninstall`. This library is powering very large apps and is used a lot, so I'm quite confident that the issue is not at this end. I'll close this PR for now.

**Comment by Shirley89** [comment]
@wnr I am afraid what @xxx said is what I met, and maybe [react-sizeme](https://github.com/ctrlplusb/react-sizeme) use invalid of this library, could we just fix to be compatible with unexpected situation?

**Comment by wnr** [comment]
@Shirley89 No sorry. I don't like the idea of sprinkling a lot of guards everywhere in the code just to mute errors due to invalid use. I'll gladly help you analyze your issue, but then you need to provide some more information and a minimal project reproducing the issue.

**Comment by Shirley89** [comment]
@wnr OK, u r right

**Pull request closed without merging**
