### PR TITLE
getComputedStyle can be null in firefox

### PR DESCRIPTION
**Pull request by SeeThruHead**

### CODE REVIEW

**Comment by wnr** [comment]
Hi and thanks for the PR. I'm a bit unsure how the algorithm would behave in case that the style object is undefined (or {} with your edits). I would like to create a minimal test case for this to ensure that everything works as expected. Would this be possible?

**Comment by SeeThruHead** [comment]
i don't know about how the behaviour will fall down, i haven't had time to delve deeper into it. What i do know is that this pr fixes my application in firefox without affecting other browsers. For one usecase. I dunno if that's good enough reason to merge it though. I'm just reluctant to change my dep to my fork is all.

**Comment by wnr** [comment]
See #68

**Comment by xaviervia** [comment]
Please reopen as per https://github.com/wnr/element-resize-detector/issues/68#issuecomment-290393017

**Pull request closed without merging**
